version: '2'

services: 

  wordpress: 
    image: pattonwebz/wordpress-php7-1-apache-memcached
    ports:
      - 80
    environment: 
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_HOST: mysql_${HOST_NAME}:3306
      VIRTUAL_HOST: ${DOMAIN_NAME},www.${DOMAIN_NAME}
      LETSENCRYPT_HOST: ${DOMAIN_NAME},www.${DOMAIN_NAME} 
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
    volumes: 
      - data_volume:/var/www/html
      - ./home/wp:/home/wp
    links:
      - mysql:mysql_${HOST_NAME}
    networks:
      - proxy-net
      - db-net

  wp:
    image: pattonwebz/docker-wpcli
    volumes_from:
      - wordpress
    links:
      - mysql:mysql_${HOST_NAME}
    entrypoint: wp
    command: "--info"

volumes:
    data_volume:

networks:
  default:
    external:
      name: proxy-net
    external:
      name: db-net
    
