version: '2'

services: 

  mysql:
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#      MYSQL_DATABASE: ${MYSQL_DATABASE} 
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data: 

networks:
  default:
    external:
      name:db-net 
    
